### ISSUE TITLE
Problems with running example

### ISSUE THREAD

**Issue by Pawlak00** [Ro6ertWcislo/AutoESN#14]
While running [example](https://github.com/Ro6ertWcislo/AutoESN/blob/master/src/auto_esn/examples/multidim_input.py)
following error occurs:

`Dimension out of range (expected to be in range of [-1, 0], but got 1)`

Error occurs only when multidimensional data is used.

**Comment by Ro6ertWcislo** [comment]
Hi, can you provide some more information?
Whole stacktrace would be useful, also do you have the same environment as in requirement.txt?
I pasted the example into colab and it seems to be working:
https://colab.research.google.com/drive/1NvjkqyBo-qEcGcOVlFugprB1k5nox1qS?usp=sharing

**Comment by Pawlak00** [comment]
My bad, some problems with dependencies probably.
