### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by coderGoOn** [Ro6ertWcislo/AutoESN#3]
I‘m really interested in you paper named "Grouped Multi-Layer Echo State Networks with Self-Normalizing Activations",but I cannot search it at web of science.

**Comment by Ro6ertWcislo** [comment]
Hi, thanks for reaching out :) 
This paper was published on ICCS 2021: https://www.iccs-meeting.org/iccs2021/ which is still running (16-18.06), so the paper should be available in a couple of days.
However, could just send you a .pdf copy :)

**Comment by Ro6ertWcislo** [comment]
You've probably found it already or forgot, but just in case the pdf is accesible here: https://www.iccs-meeting.org/archive/iccs2021/papers/127420093.pdf
